apiVersion: apps/v1
kind: Deployment
metadata:
  name: dolly-app-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dolly-app
  template:
    metadata:
      labels:
        app: dolly-app
    spec:
      containers:
      - name: dolly-app
        image: docker.io/aiprasad/myapp
        ports:
        - containerPort: 80
        env:
        - name: FLASK_ENV
          value: production
      tolerations:
      - key: node-role.kubernetes.io/control-plane
        operator: Exists
        effect: NoSchedule



